# Generated by Django 2.2.5 on 2019-10-06 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('adress', models.CharField(max_length=50)),
                ('is_delete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('decide', models.BooleanField()),
                ('adress', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
                ('userid', models.CharField(max_length=30)),
                ('borth', models.DateField()),
                ('gender', models.BooleanField()),
                ('blanknum', models.CharField(max_length=50)),
                ('lastlogintime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paopaoapp.CarBug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paopaoapp.UserInfo')),
            ],
        ),
        migrations.AddField(
            model_name='carbug',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paopaoapp.UserInfo'),
        ),
    ]
